package com.Merlin.Inventory.Management.System.Notification;

public enum NotificationType {
    LOW_STOCK,
    RESTOCK_REQUEST,
    STOCK_APPROVED,
    STOCK_REJECTED,
    STOCK_ADJUSTMENT_REQUEST,
    STOCK_ADJUSTMENT_REJECTED,
    STOCK_ADJUSTMENT_APPROVED,
    TRANSACTION_FAILED,
    TRANSACTION_SUCCESS,
    DAILY_SALES
}
