logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

spring:
  application:
    name: Inventory-Management-System
  datasource:
    url: jdbc:mysql://localhost:3306/INVENTORY_SYSTEM
    username: merlin
    password: merlin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: mungailawrence52@gmail.com
    password: srwzujhkgcxmnwto
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: qssL31Qgw5DUn/XySPLlMzH2Itidp3ItCOCfdz5gaCWxBw1EdhUFK7fREYyl+kuIpAzQ+3dwnPHHw/qgkWXy0w==
  expiration: 840000
mpesa:
    consumer-key: CGIlnd5x5uN7QryC91gutqawFojWNqo8fduTVonA3uz9L05O
    consumer-secret: wYk2AApynB1UMBOVzGL4zY3nVaWkI36uftEO3BpksihUtAK00DbojmA7cUGBrA84
    short-code: 174379
    passkey: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
    callback-url: http://localhost:8080/api/mpesa/callback